language: node_js
sudo: required
env:
  - CXX=g++-4.8
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential libudev-dev libusb-1.0-0-dev g++-4.8 gcc-4.8  
  - npm install -g gulp
node_js:
  - "node"
